goog.provide('bb_web_ds_tools.theme');
bb_web_ds_tools.theme.colors = cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"bg-item-hover","bg-item-hover",-285946042),new cljs.core.Keyword(null,"bg-button-danger","bg-button-danger",-991803447),new cljs.core.Keyword(null,"bg-table-head","bg-table-head",514051466),new cljs.core.Keyword(null,"border-default","border-default",1449646666),new cljs.core.Keyword(null,"bg-sidebar","bg-sidebar",-1016595894),new cljs.core.Keyword(null,"bg-button-xs","bg-button-xs",1049435818),new cljs.core.Keyword(null,"bg-button-primary","bg-button-primary",1669795755),new cljs.core.Keyword(null,"text-disabled","text-disabled",183511149),new cljs.core.Keyword(null,"text-muted","text-muted",1792287758),new cljs.core.Keyword(null,"bg-button-danger-hover","bg-button-danger-hover",-29136274),new cljs.core.Keyword(null,"bg-table-row-hover","bg-table-row-hover",1014470607),new cljs.core.Keyword(null,"text-button","text-button",-739025456),new cljs.core.Keyword(null,"bg-page","bg-page",-494934192),new cljs.core.Keyword(null,"text-accent","text-accent",-1336076432),new cljs.core.Keyword(null,"bg-table-body","bg-table-body",-1917742255),new cljs.core.Keyword(null,"text-primary","text-primary",803135474),new cljs.core.Keyword(null,"border-focus-accent","border-focus-accent",-1331849997),new cljs.core.Keyword(null,"bg-button-hover","bg-button-hover",2139463251),new cljs.core.Keyword(null,"text-button-primary","text-button-primary",-479213996),new cljs.core.Keyword(null,"text-danger","text-danger",-14489483),new cljs.core.Keyword(null,"bg-button-xs-hover","bg-button-xs-hover",-1231631787),new cljs.core.Keyword(null,"border-main","border-main",1910799029),new cljs.core.Keyword(null,"bg-input","bg-input",837541845),new cljs.core.Keyword(null,"bg-button","bg-button",40627543),new cljs.core.Keyword(null,"border-subtle","border-subtle",846351063),new cljs.core.Keyword(null,"bg-button-primary-hover","bg-button-primary-hover",572669687),new cljs.core.Keyword(null,"bg-button-disabled","bg-button-disabled",2101311672),new cljs.core.Keyword(null,"text-secondary","text-secondary",1760912760),new cljs.core.Keyword(null,"bg-card","bg-card",-1712632517),new cljs.core.Keyword(null,"border-focus","border-focus",1574882299),new cljs.core.Keyword(null,"bg-toolbar","bg-toolbar",1215731038),new cljs.core.Keyword(null,"ring-focus","ring-focus",863449502),new cljs.core.Keyword(null,"text-code","text-code",1208523231),new cljs.core.Keyword(null,"border-hover","border-hover",1005165343)],["#4f4f4f","#cc9393","#383838","#4f4f4f","#303030","#4f4f4f","#9fc59f","#4f4f4f","#5c888b","#dfaf8f","#383838","#dcdccc","#383838","#f0dfaf","#303030","#dcdccc","#f0dfaf","#5c888b","#383838","#cc9393","#5c888b","#4f4f4f","#303030","#4f4f4f","#4f4f4f","#afd8af","#303030","#dfaf8f","#4f4f4f","#8cd0d3","#303030","#8cd0d3","#8cd0d3","#8cd0d3"]);
/**
 * Retrieves the hex color code for a given semantic key.
 * 
 *   Args:
 *  k (keyword): The semantic color key (e.g., :bg-page).
 * 
 *   Returns:
 *  string: The hex color code, or nil if not found.
 */
bb_web_ds_tools.theme.color = (function bb_web_ds_tools$theme$color(k){
return cljs.core.get.cljs$core$IFn$_invoke$arity$2(bb_web_ds_tools.theme.colors,k);
});
bb_web_ds_tools.theme.bg_page = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-page","bg-page",-494934192).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_sidebar = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-sidebar","bg-sidebar",-1016595894).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_card = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-card","bg-card",-1712632517).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_input = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-input","bg-input",837541845).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_toolbar = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-toolbar","bg-toolbar",1215731038).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_table_head = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-table-head","bg-table-head",514051466).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_table_body = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-table-body","bg-table-body",-1917742255).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_table_row_hover = ["hover:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-table-row-hover","bg-table-row-hover",1014470607).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_item_hover = ["hover:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-item-hover","bg-item-hover",-285946042).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button","bg-button",40627543).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_hover = ["hover:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-hover","bg-button-hover",2139463251).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_primary = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-primary","bg-button-primary",1669795755).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_primary_hover = ["hover:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-primary-hover","bg-button-primary-hover",572669687).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_danger = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-danger","bg-button-danger",-991803447).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_danger_hover = ["hover:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-danger-hover","bg-button-danger-hover",-29136274).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_xs = ["bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-xs","bg-button-xs",1049435818).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_xs_hover = ["hover:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-xs-hover","bg-button-xs-hover",-1231631787).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.bg_button_disabled = ["disabled:bg-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"bg-button-disabled","bg-button-disabled",2101311672).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_primary = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-primary","text-primary",803135474).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_secondary = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-secondary","text-secondary",1760912760).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_accent = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-accent","text-accent",-1336076432).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_code = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-code","text-code",1208523231).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_muted = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-muted","text-muted",1792287758).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_danger = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-danger","text-danger",-14489483).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_disabled = ["disabled:text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-disabled","text-disabled",183511149).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_button = ["text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-button","text-button",-739025456).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.text_button_primary = ["!text-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"text-button-primary","text-button-primary",-479213996).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.border_main = ["border-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"border-main","border-main",1910799029).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.border_subtle = ["border-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"border-subtle","border-subtle",846351063).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.border_default = ["border-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"border-default","border-default",1449646666).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.border_hover = ["hover:border-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"border-hover","border-hover",1005165343).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.border_focus = ["focus:border-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"border-focus","border-focus",1574882299).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.border_focus_accent = ["focus:border-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"border-focus-accent","border-focus-accent",-1331849997).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.ring_focus = ["focus:ring-[",cljs.core.str.cljs$core$IFn$_invoke$arity$1(new cljs.core.Keyword(null,"ring-focus","ring-focus",863449502).cljs$core$IFn$_invoke$arity$1(bb_web_ds_tools.theme.colors)),"]"].join('');
bb_web_ds_tools.theme.outline_none = "focus:outline-none";
bb_web_ds_tools.theme.zenburn = cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword("bb-web-ds-tools.theme","diff-remove","bb-web-ds-tools.theme/diff-remove",563091268),new cljs.core.Keyword("bb-web-ds-tools.theme","background","bb-web-ds-tools.theme/background",1016235781),new cljs.core.Keyword("bb-web-ds-tools.theme","background2","bb-web-ds-tools.theme/background2",-197383866),new cljs.core.Keyword("bb-web-ds-tools.theme","package","bb-web-ds-tools.theme/package",385220232),new cljs.core.Keyword("bb-web-ds-tools.theme","symbol","bb-web-ds-tools.theme/symbol",827018602),new cljs.core.Keyword("bb-web-ds-tools.theme","number","bb-web-ds-tools.theme/number",-309038900),new cljs.core.Keyword("bb-web-ds-tools.theme","diff-add","bb-web-ds-tools.theme/diff-add",-617408210),new cljs.core.Keyword("bb-web-ds-tools.theme","string","bb-web-ds-tools.theme/string",1496885044),new cljs.core.Keyword("bb-web-ds-tools.theme","keyword","bb-web-ds-tools.theme/keyword",6462773),new cljs.core.Keyword("bb-web-ds-tools.theme","exception","bb-web-ds-tools.theme/exception",-1677100554),new cljs.core.Keyword("bb-web-ds-tools.theme","boolean","bb-web-ds-tools.theme/boolean",-576081002),new cljs.core.Keyword("bb-web-ds-tools.theme","uri","bb-web-ds-tools.theme/uri",-500913257),new cljs.core.Keyword("bb-web-ds-tools.theme","border","bb-web-ds-tools.theme/border",1714448313),new cljs.core.Keyword("bb-web-ds-tools.theme","namespace","bb-web-ds-tools.theme/namespace",-1179516902),new cljs.core.Keyword("bb-web-ds-tools.theme","text","bb-web-ds-tools.theme/text",1169202269),new cljs.core.Keyword("bb-web-ds-tools.theme","tag","bb-web-ds-tools.theme/tag",50610303)],["#cc9393","#383838","#303030","#8cd0d3","#dcdccc","#8cd0d3","#9fc59f","#cc9393","#afd8af","#cc9393","#bfebbf","#dfaf8f","#4f4f4f","#5c888b","#dcdccc","#f0dfaf"]);

//# sourceMappingURL=bb_web_ds_tools.theme.js.map
