(ns clj-yavl.schema.vega-lite.mark
  (:require [clj-yavl.schema.vega-lite.primitives :as primitives]
            [clj-yavl.schema.vega-lite.expr :as expr]
            [clj-yavl.schema.vega-lite.common :as common]))

(def ExprRef expr/ExprRef)
(def TextBaseline common/TextBaseline)
(def Align common/Align)
(def Color common/Color)
(def Gradient common/Gradient)
(def TextDirection common/TextDirection)
(def Cursor common/Cursor)
(def MarkInvalidDataMode common/MarkInvalidDataMode)
(def Interpolate common/Interpolate)
(def FontStyle common/FontStyle)
(def FontWeight common/FontWeight)
(def StrokeJoin common/StrokeJoin)
(def SymbolShape common/SymbolShape)
(def URI common/URI)
(def StrokeCap common/StrokeCap)
(def Blend common/Blend)
(def TooltipContent common/TooltipContent)
(def Text common/Text)
(def Orientation common/Orientation)
(def RelativeBandSize common/RelativeBandSize)
(def Mark common/Mark)

(def OverlayMarkDef
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:y2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:clip {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radiusOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:x2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:style {:optional true} [:or string? [:vector string?]]]
   [:thetaOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:yOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]
   [:xOffset {:optional true} [:or number? [:ref #'ExprRef]]]])

(def MarkDef
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:y2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:discreteBandSize {:optional true} [:or number? [:ref #'RelativeBandSize]]]
   [:thickness {:optional true} number?]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:clip {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:binSpacing {:optional true} number?]
   [:radiusOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:bandSize {:optional true} number?]
   [:width {:optional true}
    [:or number? [:ref #'ExprRef] [:ref #'RelativeBandSize]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:type [:ref #'Mark]] [:continuousBandSize {:optional true} number?]
   [:cornerRadiusEnd {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:x2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:style {:optional true} [:or string? [:vector string?]]]
   [:thetaOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:line {:optional true} [:or boolean? [:ref #'OverlayMarkDef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:minBandSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:point {:optional true}
    [:or boolean? [:ref #'OverlayMarkDef] [:enum "transparent"]]]
   [:yOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius2Offset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true}
    [:or number? [:ref #'ExprRef] [:ref #'RelativeBandSize]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]
   [:xOffset {:optional true} [:or number? [:ref #'ExprRef]]]])

(def ErrorBar primitives/ErrorBar)
(def ErrorBand primitives/ErrorBand)
(def BoxPlot primitives/BoxPlot)

(def CompositeMark [:or [:ref #'BoxPlot] [:ref #'ErrorBar] [:ref #'ErrorBand]])

(def LineConfig
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:point {:optional true}
    [:or boolean? [:ref #'OverlayMarkDef] [:enum "transparent"]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]])

(def RectConfig
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:discreteBandSize {:optional true} [:or number? [:ref #'RelativeBandSize]]]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:binSpacing {:optional true} number?]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:continuousBandSize {:optional true} number?]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:minBandSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]])

(def TickConfig
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:discreteBandSize {:optional true} [:or number? [:ref #'RelativeBandSize]]]
   [:thickness {:optional true} number?]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:binSpacing {:optional true} number?]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:bandSize {:optional true} number?]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:continuousBandSize {:optional true} number?]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:minBandSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]])

(def BarConfig
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:discreteBandSize {:optional true} [:or number? [:ref #'RelativeBandSize]]]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:binSpacing {:optional true} number?]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:continuousBandSize {:optional true} number?]
   [:cornerRadiusEnd {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:minBandSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]])

(def MarkConfig
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]])

(def AreaConfig
  [:map {:closed true}
   [:y {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:description {:optional true} [:or string? [:ref #'ExprRef]]]
   [:baseline {:optional true} [:or [:ref #'TextBaseline] [:ref #'ExprRef]]]
   [:smooth {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:padAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:startAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aspect {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:cornerRadiusBottomRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRoleDescription {:optional true} [:or string? [:ref #'ExprRef]]]
   [:align {:optional true} [:or [:ref #'Align] [:ref #'ExprRef]]]
   [:stroke {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:dx {:optional true} [:or number? [:ref #'ExprRef]]]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dir {:optional true} [:or [:ref #'TextDirection] [:ref #'ExprRef]]]
   [:innerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:limit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandSize {:optional true} number?]
   [:fill {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef] nil?]]
   [:strokeDash {:optional true} [:or [:vector number?] [:ref #'ExprRef]]]
   [:time {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ellipsis {:optional true} [:or string? [:ref #'ExprRef]]]
   [:width {:optional true} [:or number? [:ref #'ExprRef]]]
   [:dy {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cursor {:optional true} [:or [:ref #'Cursor] [:ref #'ExprRef]]]
   [:lineBreak {:optional true} [:or string? [:ref #'ExprRef]]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:fillOpacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:strokeMiterLimit {:optional true} [:or number? [:ref #'ExprRef]]]
   [:timeUnitBandPosition {:optional true} number?]
   [:interpolate {:optional true} [:or [:ref #'Interpolate] [:ref #'ExprRef]]]
   [:angle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeDashOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta {:optional true} [:or number? [:ref #'ExprRef]]]
   [:radius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:theta2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:font {:optional true} [:or string? [:ref #'ExprRef]]]
   [:size {:optional true} [:or number? [:ref #'ExprRef]]]
   [:outerRadius {:optional true} [:or number? [:ref #'ExprRef]]]
   [:aria {:optional true} [:or boolean? [:ref #'ExprRef]]]
   [:line {:optional true} [:or boolean? [:ref #'OverlayMarkDef]]]
   [:strokeWidth {:optional true} [:or number? [:ref #'ExprRef]]]
   [:opacity {:optional true} [:or number? [:ref #'ExprRef]]]
   [:fontStyle {:optional true} [:or [:ref #'FontStyle] [:ref #'ExprRef]]]
   [:fontWeight {:optional true} [:or [:ref #'FontWeight] [:ref #'ExprRef]]]
   [:strokeJoin {:optional true} [:or [:ref #'StrokeJoin] [:ref #'ExprRef]]]
   [:shape {:optional true}
    [:or [:or [:ref #'SymbolShape] string?] [:ref #'ExprRef]]]
   [:url {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:order {:optional true} [:or nil? boolean?]]
   [:cornerRadiusTopLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:cornerRadiusBottomLeft {:optional true} [:or number? [:ref #'ExprRef]]]
   [:point {:optional true}
    [:or boolean? [:ref #'OverlayMarkDef] [:enum "transparent"]]]
   [:lineHeight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:strokeCap {:optional true} [:or [:ref #'StrokeCap] [:ref #'ExprRef]]]
   [:x {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:cornerRadiusTopRight {:optional true} [:or number? [:ref #'ExprRef]]]
   [:blend {:optional true} [:or [:ref #'Blend] [:ref #'ExprRef]]]
   [:fontSize {:optional true} [:or number? [:ref #'ExprRef]]]
   [:ariaRole {:optional true} [:or string? [:ref #'ExprRef]]]
   [:endAngle {:optional true} [:or number? [:ref #'ExprRef]]]
   [:y2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "height"]]]
   [:filled {:optional true} boolean?]
   [:radius2 {:optional true} [:or number? [:ref #'ExprRef]]]
   [:x2 {:optional true} [:or number? [:ref #'ExprRef] [:enum "width"]]]
   [:href {:optional true} [:or [:ref #'URI] [:ref #'ExprRef]]]
   [:tooltip {:optional true}
    [:or number? string? boolean? nil? [:ref #'TooltipContent]
     [:ref #'ExprRef]]]
   [:strokeOffset {:optional true} [:or number? [:ref #'ExprRef]]]
   [:height {:optional true} [:or number? [:ref #'ExprRef]]]
   [:text {:optional true} [:or [:ref #'Text] [:ref #'ExprRef]]]])

(def AnyMarkConfig
  [:or [:ref #'MarkConfig] [:ref #'AreaConfig] [:ref #'BarConfig]
   [:ref #'RectConfig] [:ref #'LineConfig] [:ref #'TickConfig]])

(def ErrorBarExtent primitives/ErrorBarExtent)

(def ErrorBandDef
  [:map {:closed true} [:clip {:optional true} boolean?]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:tension {:optional true} number?]
   [:band {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:type [:ref #'ErrorBand]] [:orient {:optional true} [:ref #'Orientation]]
   [:interpolate {:optional true} [:ref #'Interpolate]]
   [:borders {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:opacity {:optional true} number?]
   [:extent {:optional true} [:ref #'ErrorBarExtent]]])

(def BoxPlotDef
  [:map {:closed true} [:clip {:optional true} boolean?]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:rule {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:box {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:type [:ref #'BoxPlot]]
   [:invalid {:optional true} [:or [:ref #'MarkInvalidDataMode] nil?]]
   [:orient {:optional true} [:ref #'Orientation]]
   [:outliers {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:size {:optional true} number?]
   [:median {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:opacity {:optional true} number?]
   [:extent {:optional true} [:or number? [:enum "min-max"]]]
   [:ticks {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]])

(def ErrorBarDef
  [:map {:closed true} [:thickness {:optional true} number?]
   [:clip {:optional true} boolean?]
   [:color {:optional true}
    [:or [:ref #'Color] [:ref #'Gradient] [:ref #'ExprRef]]]
   [:rule {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:type [:ref #'ErrorBar]] [:orient {:optional true} [:ref #'Orientation]]
   [:size {:optional true} number?] [:opacity {:optional true} number?]
   [:extent {:optional true} [:ref #'ErrorBarExtent]]
   [:ticks {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]])

(def CompositeMarkDef
  [:or [:ref #'BoxPlotDef] [:ref #'ErrorBarDef] [:ref #'ErrorBandDef]])

(def AnyMark
  [:or [:ref #'CompositeMark] [:ref #'CompositeMarkDef] [:ref #'Mark]
   [:ref #'MarkDef]])

(def BoxPlotConfig
  [:map {:closed true}
   [:box {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:extent {:optional true} [:or number? [:enum "min-max"]]]
   [:median {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:outliers {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:rule {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:size {:optional true} number?]
   [:ticks {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]])

(def ErrorBarConfig
  [:map {:closed true} [:extent {:optional true} [:ref #'ErrorBarExtent]]
   [:rule {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:size {:optional true} number?] [:thickness {:optional true} number?]
   [:ticks {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]])

(def ErrorBandConfig
  [:map {:closed true}
   [:band {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:borders {:optional true} [:or boolean? [:ref #'AnyMarkConfig]]]
   [:extent {:optional true} [:ref #'ErrorBarExtent]]
   [:interpolate {:optional true} [:ref #'Interpolate]]
   [:tension {:optional true} number?]])
